### ISSUE TITLE
pip installing process raising error

### ISSUE THREAD

**Issue by moshen212** [pylover/khayyam#11]
Hi,
I try to install khayyam library by `pip install khayyam==1.0.2` but i get below error:

`IOError: [Errno 2] No such file or directory: '/home/mohsen/.django-venv/build/khayyam/README.md'`

And log file contains:

------------------------------------------------------------
/home/mohsen/.django-venv/bin/pip run on Thu May  7 23:39:45 2015
Downloading/unpacking khayyam
  Getting page https://pypi.python.org/simple/khayyam/
  URLs to search for versions for khayyam:
  * https://pypi.python.org/simple/khayyam/
  Analyzing links from page https://pypi.python.org/simple/khayyam/
    Skipping link https://pypi.python.org/packages/2.7/K/Khayyam/Khayyam-0.9.1-py2.7.egg#md5=2574b3411a6e4289299e7cea92c6dc1a (from https://pypi.python.org/simple/khayyam/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/K/Khayyam/Khayyam-0.9.2-py2.7.egg#md5=0640cb5a42d89373a2207466f01f45da (from https://pypi.python.org/simple/khayyam/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/K/Khayyam/Khayyam-1.0.0-py2.7.egg#md5=885cc15c81c44bff83356304a55d3ce5 (from https://pypi.python.org/simple/khayyam/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/3.4/K/Khayyam/Khayyam-1.0.0-py3.4.egg#md5=bc8de0b504c52a30f8601d6510fa8164 (from https://pypi.python.org/simple/khayyam/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/source/K/Khayyam/Khayyam-0.9.1.tar.gz#md5=8c7a86682f79ad369a27281b059ed6ea (from https://pypi.python.org/simple/khayyam/), version: 0.9.1
    Found link https://pypi.python.org/packages/source/K/Khayyam/Khayyam-0.9.2.tar.gz#md5=dbc1ac1f21a05f3fe441a7f74a58b1bf (from https://pypi.python.org/simple/khayyam/), version: 0.9.2
    Found link https://pypi.python.org/packages/source/K/Khayyam/Khayyam-0.9.tar.gz#md5=7447507e312a7fbe8096745a5523b441 (from https://pypi.python.org/simple/khayyam/), version: 0.9
    Found link https://pypi.python.org/packages/source/K/Khayyam/Khayyam-1.0.0.tar.gz#md5=469117008a88a1d82c853dd4bec586f1 (from https://pypi.python.org/simple/khayyam/), version: 1.0.0
    Found link https://pypi.python.org/packages/source/K/Khayyam/Khayyam-1.0.2.tar.gz#md5=77794f59c29e8849d5f2fe6b495a7e2a (from https://pypi.python.org/simple/khayyam/), version: 1.0.2
  Using version 1.0.2 (newest of versions: 1.0.2, 1.0.0, 0.9.2, 0.9.1, 0.9)
  Downloading Khayyam-1.0.2.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/K/Khayyam/Khayyam-1.0.2.tar.gz#md5=77794f59c29e8849d5f2fe6b495a7e2a (from https://pypi.python.org/simple/khayyam/)
  Running setup.py (path:/home/mohsen/.django-venv/build/khayyam/setup.py) egg_info for package khayyam
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/mohsen/.django-venv/build/khayyam/setup.py", line 27, in <module>
        long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),
    IOError: [Errno 2] No such file or directory: '/home/mohsen/.django-venv/build/khayyam/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/mohsen/.django-venv/build/khayyam/setup.py", line 27, in <module>

    long_description=open(os.path.join(os.path.dirname(__file__), 'README.md')).read(),

IOError: [Errno 2] No such file or directory: '/home/mohsen/.django-venv/build/khayyam/README.md'

----------------------------------------
Cleaning up...
  Removing temporary dir /home/mohsen/.django-venv/build...
Command python setup.py egg_info failed with error code 1 in /home/mohsen/.django-venv/build/khayyam
Exception information:
Traceback (most recent call last):
  File "/home/mohsen/.django-venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/mohsen/.django-venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/mohsen/.django-venv/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/home/mohsen/.django-venv/local/lib/python2.7/site-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/mohsen/.django-venv/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /home/mohsen/.django-venv/build/khayyam

**Comment by pylover** [comment]
Fixed in 1.0.3

**Comment by moshen212** [comment]
thanks pylover.
