### ISSUE TITLE
Can not install using pip on FreeBSD 10.1

### ISSUE THREAD

**Issue by kamyar1979** [pylover/khayyam#15]
pip install khayyam
Collecting khayyam
  Using cached Khayyam-2.9.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-h6370fyd/khayyam/setup.py", line 24, in <module>
        long_description=open(os.path.join(os.path.dirname(__file__), 'README.rst')).read(),
      File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 796: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h6370fyd/khayyam

**Comment by kamyar1979** [comment]
Workaround:

env LANG=en_US.UTF-8 pip install khayyam

**Comment by pylover** [comment]
Thanks , a lot.

So, you have to wait, to i test it on freeBSD.

**Comment by pylover** [comment]
I tested It on the FreeBSD 10.1, Just now:

$ pip install khayyam
Successfully installed khayyam-2.6.9.

$ echo $LANG
LANG: undefined variable.

**Comment by kamyar1979** [comment]
You have to test it on python3.4
pip3.4 install khayyam

LANG is not set by default, but if you set it the problem fixes.

**Comment by pylover** [comment]
$ pip --version
7.1.2

**Comment by pylover** [comment]
OK, i am trying to install python3 on my BSD.

So, what's you suggestion to a persistent solution? may be 
encoding/decoding readme. or what else?

**Comment by pylover** [comment]
fixed using `open(fn, encoding='UTF-8')`
