### ISSUE TITLE
from khayyam.algorithms import days_in_month doesn't work in the latest version

### ISSUE THREAD

**Issue by eteamin** [pylover/khayyam#21]
I had to go back to 2.10.0 for twa to work.
ImportError: cannot import name days_in_month

**Comment by pylover** [comment]
Please consider the semver.org.

The major version just changed. it's mean the 3.x.x is NOT COMPATTIBLE with 2.x.x.

The mentioned function has been renamed in the new release to `get_days_in_jalali_month`

**Comment by eteamin** [comment]
ba labele invalid asan takhrib kardiii :D
I read the versioning convention. thanks
