### ISSUE TITLE
Hash of JalaliDate collides too easily

### ISSUE THREAD

**Issue by mwchase** [pylover/khayyam#24]
Seen in [a StackOverflow question](http://stackoverflow.com/questions/40950709/persian-calendar-python):

```
from khayyam import *

print(JalaliDate(1389, 2, 18) == JalaliDate(1391, 12, 30))
```

The expected result is False, but the actual result is True. Because JalaliDates are compared by hash, and the hash is done by bitwise XOR, many hashes, and therefore many dates, can collide.

**Comment by pylover** [comment]
Thanks for reporting.
