### ISSUE TITLE
مشکل در پیدا کردن تعداد روزهای ماه فعلی

### ISSUE THREAD

**Issue by ehsankhorasani** [pylover/khayyam#27]
سلام
من میخوام تعداد روزهای ماه فعلی رو پیدا کنم
مثلا با این تابع:
`source_date = JalaliDate(1394, 3, 24)`
`print JalaliDate(source_date.year, source_date.month, source_date.day).daysinmonth()`

ولی ارور میده که 
`TypeError: 'long' object is not callable`
ظاهرا نمیشه مستقیما از تابع دیس‌مانس استفاده کرد. درسته؟

**Comment by pylover** [comment]
Hi, Thank's for the contribution.

As you see in the [documentations](http://khayyam.dobisel.com/api.html#khayyam.JalaliDate.daysinmonth)

The `JalaliDate.daysinmonth` is not a callable/method. So please do not try to call it.

```python
source_date = JalaliDate(1394, 3, 24)
print JalaliDate(source_date.year, source_date.month, source_date.day).daysinmonth
31
```
