### ISSUE TITLE
How can I understand this month is 29 days or 30 or 31?

### ISSUE THREAD

**Issue by GreatBahram** [pylover/khayyam#28]
Hi
Thank you for this beautiful module. I was wonder how can I understand this month is 29, 30 or 31 days month?
Without some tricks like using `timedelta` and ... .
Thanks

**Comment by pylover** [comment]
HI, sorry for the late: 

As you see in the [documentation](http://khayyam.dobisel.com/api.html#khayyam.JalaliDate.daysinmonth), you can use the `daysinmonth` property.

But another approach is to use the low-level algorithms directly:
```python
from khayyam import algorithms_c as alg
# OR
from khayyam import algorithms_pure as alg

print(alg.get_days_in_jalali_month(1361, 6))
```

**Comment by GreatBahram** [comment]
Thank you
