### ISSUE TITLE
problem in JalaliDatetime.now(tz=TehranTimezone())

### ISSUE THREAD

**Issue by zarinpy** [pylover/khayyam#29]
if we use  JalaliDatetime.now(tz=TehranTimezone()) to get tehran time
we will see time is one hour earlier
```python
>>> khayyam.JalaliDatetime(1396, 10, 12, 16, 4, 49, 783911, tzinfo=+03:30 dst:60, Seshanbeh) 
```
i'm using version 3.0.15

**Comment by eteamin** [comment]
@zarinpy It explicitly mentions that `dst` is 60 minutes.
https://en.wikipedia.org/wiki/Daylight_saving_time
