### ISSUE TITLE
do we have total_seconds?

### ISSUE THREAD

**Issue by sae13** [pylover/khayyam#31]
from khayyam import JalaliDatetime as jDatetime;
herBirthday = jDatetime(1396, 10, 24, 23, 59, 55);
now = jDatetime.now();
delta = herBrthday - now;

how I can have delta.total_seconds?

**Comment by pylover** [comment]
Please check the Python's documentation:

https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds
