### ISSUE TITLE
parsing problem?

### ISSUE THREAD

**Issue by Aquarii** [pylover/khayyam#37]
hi. 
I try to parse the date column in pandas using strptime like this:
for i in p.index:
    p['jdate'][i] = JalaliDatetime.strptime(p['تاریخ'].iloc[i], '%Y/%m/%d')
but except some results in the beginning of the dataframe the others are incorrect. why is this happening? am I doing it wrong or what? 
![image](https://user-images.githubusercontent.com/8092720/109429636-f4801700-7a11-11eb-9821-62c46ffc85f5.png) ![image](https://user-images.githubusercontent.com/8092720/109429603-be429780-7a11-11eb-8cac-76b7b16182aa.png)
any help is appreciated.

**Comment by akhorshidi** [comment]
Maybe I'm a little late but I hope this can help someone else: 

`df.index = [JalaliDate.strptime(x, '%Y/%m/%d') for x in df.index]`

**Comment by pylover** [comment]
Please provide a simple code snippet about how to produce the issue. without mention anything about the outside of the `Khayyam`'s domain. for example: not to say anything about what you want to do and mentioning the ``Pandas``. 

An example of good error reporting: brython-dev/brython#1713

**Comment by pylover** [comment]
And, please provide text instead of images.
