### ISSUE TITLE
Resamplig on JalaliDate Time Index

### ISSUE THREAD

**Issue by akhorshidi** [pylover/khayyam#38]
I was wondering is there any idea about how to do resampling on `khayyam.jalali_date.JalaliDate` time indices?

You may try the code below to reproduce the issue:

```
from datetime import timedelta
from khayyam import JalaliDate, JalaliDatetime
import pandas as pd

start_date_jalali = JalaliDate(1399, 5, 1)
end_date_jalali = JalaliDate(1400, 5, 31)
date = [start_date_jalali + timedelta(days=i) for i in range((end_date_jalali - start_date_jalali).days + 1)]
df = pd.DataFrame(index=date, columns=[])
df.index.name = 'Date'

df.resample('M')
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
```

**Comment by pylover** [comment]
Please provide a simple code snippet about how to produce the issue, what you expect and what you get, including the platform information. without mention anything about the outside of the Khayyam's domain. for example: not to say anything about what you want to do and not mention the `Pandas` and any other project.

Take a look at the current page's URL:  Thw `/khayyam` means you have to just talk about the `Khayyam`.  

An example of good error reporting: brython-dev/brython#1713

**Comment by akhorshidi** [comment]
Thank you for your comment. Do you mean this is a Pandas issue and Khayyam developers are reluctant to improve consistency with other packages?!  I would be grateful,  and I am sure the community would be grateful, if one can add such a feature to Khayyam. So, I suggest you reopen the issue and give the label `fueature-request ` to it.

**Comment by akhorshidi** [comment]
Thank you for your comment. Do you mean this is a Pandas issue and Khayyam developers are reluctant to improve consistency with other packages?!  I would be grateful,  and I am sure the community would be grateful, if one can add such a feature to Khayyam. Anyway, I suggest you reopen the issue and give the label `fueature-request ` to it.

**Comment by pylover** [comment]
If any API is not working as expected(documentation), this is a bug.

else:

`Khayyam` is a dependency of your project and `Pandas` is a dependency too(as well as the Khayyam). There is no reason to `Khayyam` kept aligned with `Pandas`.

If you need a feature, please remove anything about the `Pandas`. and describe your requirements.

**Comment by pylover** [comment]
And please close this one and reopen another issue with title: `Feature Request: .*`.

**Comment by pylover** [comment]
May helps:

An important rule in software architecture is:

`Dependant` depends on  `Dependency`.

So, `Dependant` will follow/track the `Dependency` not visa-verse.

**Comment by akhorshidi** [comment]
> 
> 
> May helps:
> 
> An important rule in software architecture is:
> 
> `Dependant` depends on `Dependency`.
> 
> So, `Dependant` will follow/track the `Dependency` not visa-verse.

I relatively agree but I do think `Dependency` developers are the best people who can add such functionality to `Dependant` . Anyway I prefer to close this one. Thank you for your attention.

**Comment by pylover** [comment]
If you need a feature, please describe your requirements in form of one or more BDD test cases.

### Example

```
Given Foo
When: + Bar
Then: FooBar
```
