### ISSUE TITLE
Incorrect Zero Padding

### ISSUE THREAD

**Issue by Bersam** [pylover/khayyam#7]
Due documentation, "%H:%M:%S" should give me zero padded Hour:Min:Sec, but i'm getting this "2:20:0" instead of this "02:20:00".

In [45]: khayyam.JalaliDatetime.now().strftime("%H:%M:%S")
Out[45]: '14:18:2'
In [46]: datetime.datetime.now().strftime("%H:%M:%S")
Out[46]: '14:18:02'

**Comment by pylover** [comment]
Fixed
